language: python

python:
  - '3.6'

before_install:
  - pip install --upgrade pytest

install:
  - pip install hypothesis pytest-cov python-coveralls

before_script:
  - export PYTHONPATH=.

script:
  - pytest tests

after_success:
  - pytest --cov=chinese tests
  - coverage report
  - coveralls
